config/routes.rb
Rails.application.routes.draw do
  resources :game_imports, :only => [:create, :destroy, :show, :index, :new]

  devise_for :users

  get 'arena_card_decks/stats' => 'arena_card_decks#stats'
  resources :arena_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  resources :regular_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  root :to => 'home#index'
end

app/models/regular_card_deck.rb
class RegularCardDeck < CardDeck

  validates :name, :length => { :maximum => 64 }, :presence => true

  def before_card_added(added_card)
    if self.cards.where(:id => added_card.id).count >= 2
      raise Exception.new('Deck can only contain 2 of each card')
    end
  end

  def add_games?
    true
  end

end

app/controllers/regular_card_decks_controller.rb
class RegularCardDecksController < CardDecksBaseController

  def controller_model
    RegularCardDeck
  end

  def editable_fields
    [:name]
  end

end

app/views/regular_card_decks/_form.html.erb
<%= form_for(@regular_card_deck) do |f| %>
  <% if @regular_card_deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regular_card_deck.errors.count, "error") %> prohibited this Card Deck from being saved:</h2>

      <ul>
      <% @regular_card_deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group"">
    <label for="regular_card_deck_hero_id">Hero</label>
    <%= f.collection_select :hero_id, @heroes, :id, :display_name, { :selected => @regular_card_deck.hero_id }, { :class => 'form-control' } %>
  </div>

  <div class="form-group">
    <label for="name">Name</label>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <br />
<% end %>

app/views/regular_card_decks/edit.html.erb
<h1>Editing <%= @regular_card_deck.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @regular_card_deck %> |
<%= link_to 'Back', regular_card_decks_path %>

app/views/regular_card_decks/index.html.erb
<div class="row">
    <h1>Regular Card Decks</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Hero</th>
          <th>Start Date</th>
          <th>Wins</th>
          <th>Losses</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
        <% @regular_card_decks.each do |regular_card_deck| %>
          <tr class="link-row" data-href="<%= url_for regular_card_deck %>">
            <td><%= regular_card_deck.name %></td>
            <td><%= regular_card_deck.hero.display_name %></td>
            <td><%= regular_card_deck.created_at.to_formatted_s(:date) %></td>
            <td><%= regular_card_deck.num_games_won %></td>
            <td><%= regular_card_deck.num_games_lost %></td>
            <td>
              <%= link_to(regular_card_deck, method: :delete, data: { confirm: 'Are you sure?' }) do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %> 
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @regular_card_decks %>

    <br>

    <%= link_to 'New Card Deck', new_regular_card_deck_path %>

</div>

app/views/regular_card_decks/new.html.erb
<h1>New Regular Card Deck</h1>

<%= render 'form' %>

<%= link_to 'Back', regular_card_decks_path %>

app/views/regular_card_decks/show.html.erb
<div class="row">
    <h2><%= @regular_card_deck.name %> (<%= @regular_card_deck.hero.display_name %>)</h2>

    <% if @regular_card_deck.add_games? %>
        <div style="margin: 10px;">
            <h3>Add Game</h3>

            <%= form_for([@regular_card_deck, @game], :html => { :class => 'form-inline' }) do |f| %>
                <% if @game.errors.any? %>
                    <div id="error_explanation" class="alert alert-danger">
                        <ul>
                            <% @game.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>

                <div class="form-group">
                    <label for="game_hero_id" class="sr-only">Opponent</label>
                    <div class="col-sm-10">
                        <%= f.collection_select :hero_id, @heroes, :id, :display_name, { :selected => @game.hero_id }, { :class => 'form-control' } %>
                    </div>
                </div>

                <div class="checkbox">
                    <label>
                        <%= f.check_box :win_ind %> Win
                    </label>
                </div>

                <div class="radio">
                  <label>
                    <%= f.radio_button :mode, 'normal', :checked => true %>
                    Normal
                  </label>
                </div>
                <div class="radio">
                  <label>
                    <%= f.radio_button :mode, 'ranked' %>
                    Ranked
                  </label>
                </div>

                <%= f.submit 'Add Game', :class => 'btn btn-default' %>
            <% end %>

        </div>
    <% end %>

    <table class="table table-striped">
      <thead>
        <th>Opponent</th>
        <th>Mode</th>
        <th>Result</th>
        <th></th>
      </thead>

      <tbody>
        <% @regular_card_deck.games.order(:created_at => :desc).each do |game| %>
            <tr>
              <td><%= game.hero.display_name %></td>
              <td><%= game.mode.titleize %></td>
              <td><%= game.win_ind ? 'Win' : 'Loss' %></td>
              <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Edit', edit_regular_card_deck_path(@regular_card_deck) %> |
    <%= link_to 'Back', regular_card_decks_path %>

</div>