config/routes.rb
Rails.application.routes.draw do
  resources :game_imports, :only => [:create, :destroy, :show, :index, :new]

  devise_for :users

  get 'arena_card_decks/stats' => 'arena_card_decks#stats'
  resources :arena_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  resources :regular_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  root :to => 'home#index'
end

app/models/arena_card_deck.rb
class ArenaCardDeck < CardDeck

  MAX_LOSSES = 3
  MAX_WINS = 12

  validates :num_games_lost, :numericality => { :only_integer => true, :less_than_or_equal_to => MAX_LOSSES }
  validates :num_games_won, :numericality => { :only_integer => true, :less_than_or_equal_to => MAX_WINS }

  def add_games?
    num_games_lost < MAX_LOSSES && num_games_won < MAX_WINS
  end

  scope :completed, -> { where("num_games_lost = #{MAX_LOSSES} or num_games_won = #{MAX_WINS}") }

end

app/controllers/arena_card_decks_controller.rb
require 'num_decks_stat'
require 'avg_wins_stat'

class ArenaCardDecksController < CardDecksBaseController

  def controller_model
    ArenaCardDeck
  end

  def index
    super
    @arena_card_deck = ArenaCardDeck.new
    @heroes = Hero.order(:name => :asc)
  end

  def stats
    arena_card_decks = ArenaCardDeck.completed.where(:user_id => current_user.id)

    @num_decks = DeckStats::NumDecksStat.new(arena_card_decks)
    @avg_wins = DeckStats::AvgWinsStat.new(arena_card_decks)
  end

end

app/helpers/arena_card_decks_helper.rb
module ArenaCardDecksHelper
  def hero_name(model)
    hero_id = nil
    if model.has_attribute? :hero_id
      hero_id = model.hero_id
    else
      hero_id = model.id
    end

    heroes = @heroes || Hero.all
    heroes.find{|hero| hero.id == hero_id }.display_name
  end
end

app/views/arena_card_decks/_form.html.erb
<%= form_for(@arena_card_deck, :html => { :class => 'form-horizontal', :role => 'form' }) do |f| %>
  <% if @arena_card_deck.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @arena_card_deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="margin-bottom: 10px"">
    <%= f.collection_select :hero_id, @heroes, :id, :display_name, { :selected => @arena_card_deck.hero_id } %>
  </div>

  <div class="actions" style="margin-bottom: 10px">
    <%= f.submit %>
  </div>
<% end %>

app/views/arena_card_decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @arena_card_deck %> |
<%= link_to 'Back', arena_card_decks_path %>

app/views/arena_card_decks/index.html.erb
<div class="row">

  <div class="border-small">
    <%= form_for(@arena_card_deck, :html => { :class => 'form-inline', :role => 'form' }) do |f| %>
      <div class="form-group">
        <h4>New Deck:</h4>
      </div>
      <div class="form-group">
        <%= f.collection_select :hero_id, @heroes, :id, :display_name, { :selected => @arena_card_deck.hero_id }, { :class => 'form-control' } %>
      </div>

      <%= f.submit 'Add', :class => 'btn btn-default' %>
    <% end %>

  </div>

  <h1><%= link_to 'Arena Card Decks', arena_card_decks_stats_path %></h1>
  <table class="table linked-rows">
    <thead>
      <tr>
        <th>Hero</th>
        <th>Start Date</th>
        <th>Wins</th>
        <th>Losses</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @arena_card_decks.each do |arena_card_deck| %>
        <tr class="<%= arena_card_deck.add_games? ? 'add-games' : 'full-games' %> link-row" data-href="<%= url_for arena_card_deck %>">
          <td><%= hero_name(arena_card_deck) %></td>
          <td><%= arena_card_deck.created_at.to_formatted_s(:date) %></td>
          <td><%= arena_card_deck.num_games_won %></td>
          <td><%= arena_card_deck.num_games_lost %></td>
          <td>
            <%= link_to(arena_card_deck, method: :delete, data: { confirm: 'Are you sure?' }) do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @arena_card_decks %>

  <br>

</div>

app/views/arena_card_decks/new.html.erb
<h1>New Arena Deck</h1>

<%= render 'form' %>

<%= link_to 'Back', arena_card_decks_path %>

app/views/arena_card_decks/show.html.erb
<div class="row">
    <h2><%= hero_name(@arena_card_deck) %> (<%= @arena_card_deck.num_games_won %>-<%= @arena_card_deck.num_games_lost %>)</h2>

    <% if @arena_card_deck.add_games? %>
        <div style="margin: 10px;">
            <h3>Add Game</h3>

            <%= form_for([@arena_card_deck, @game], :html => { :class => 'form-inline' }) do |f| %>
                <% if @game.errors.any? %>
                    <div id="error_explanation" class="alert alert-danger">
                        <ul>
                            <% @game.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>

                <div class="form-group">
                    <label for="game_hero_id" class="sr-only">Opponent</label>
                    <div class="col-sm-10">
                        <%= f.collection_select :hero_id, @heroes, :id, :display_name, { :selected => @game.hero_id }, { :class => 'form-control' } %>
                    </div>
                </div>

                <div class="checkbox">
                    <label>
                        <%= f.check_box :win_ind %> Win
                    </label>
                </div>

                <%= f.hidden_field :mode, :value => 'arena' %>

                <%= f.submit 'Add Game', :class => 'btn btn-default' %>
            <% end %>

        </div>
    <% end %>

    <table class="table table-striped">
      <thead>
        <th>Opponent</th>
        <th>Result</th>
        <th></th>
      </thead>

      <tbody>
        <% @arena_card_deck.games.order(:created_at => :desc).each do |game| %>
            <tr>
              <td><%= hero_name(game) %></td>
              <td><%= game.win_ind ? 'Win' : 'Loss' %></td>
              <td>
                <%= link_to(game, method: :delete, data: { confirm: 'Are you sure?' }) do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Back', arena_card_decks_path %>

</div>

app/views/arena_card_decks/stats.html.erb
<div class="row text-center">
  <h2>Arena Runs By Hero</h2>
  <div id="numDecksChart"></div>
</div>

<div class="row text-center">
  <h2>Average Arena Wins</h2>
  <div id="avgWinsChart"></div>
</div>

<script type="text/javascript">
(function() {
  
  var avg_win_data = [];
  <% @avg_wins.by_hero.each do |stat| %>
  avg_win_data.push({
    hero_name: '<%= stat[:hero].display_name %>',
    value: <%= stat[:value] %>  
  });
  <% end %>
  avg_win_data.push({
    hero_name: 'Overall',
    value: <%= @avg_wins.total %>  
  });

  var margin = {top: 20, right: 20, bottom: 30, left: 40};
  var width = $("#avgWinsChart").width() - margin.left - margin.right;
  var height = 500 - margin.top - margin.bottom;

  var svg = d3.select("#avgWinsChart")
    .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  var xValues = avg_win_data.map(function(d) { return d.hero_name; });
  var maxY = d3.max(avg_win_data, function(d) { return d.value; });

  var x = d3.scale.ordinal().rangeRoundBands([0, width], .1).domain(xValues);
  var y = d3.scale.linear().range([height, 0]).domain([0, maxY]);

  var xAxis = d3.svg.axis().scale(x).orient("bottom");
  var yAxis = d3.svg.axis().scale(y).orient("left");

  svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis);

  svg.append("g")
    .attr("class", "y axis")
    .call(yAxis)
    .append("text")
    .attr("transform", "rotate(-90)")
    .attr("y", 6)
    .attr("dy", ".71em")
    .style("text-anchor", "end")
    .text("Avg Wins");


  svg.selectAll(".bar")
    .data(avg_win_data)
    .enter()
    .append("rect")
    .attr("class", "bar")
    .attr("x", function(d) { return x(d.hero_name); })
    .attr("width", x.rangeBand())
    .attr("y", function(d) { return y(d.value); })
    .attr("height", function(d) { return height - y(d.value); });
    
  svg.selectAll(".valueLabel")
    .data(avg_win_data)
    .enter()
    .append("text")
    .attr('text-anchor', 'middle')
    .attr('class', 'valueLabel')
    .attr("x", function(d, i) { return x(x.domain()[i]) + x.rangeBand() / 2; })
    .attr("y", function(d) { return y(d.value) - 2; })
    .text(formatValueText);

  function formatValueText(d) {
    if (d.value > 0) {
      return d.value.toFixed(1); 
    } else {
      return '';  
    }
  }
})();

(function() {
  var data = [];
  <% @num_decks.by_hero.each do |stat| %>
    data.push({
      hero_name: '<%= stat[:hero].display_name %>',
      value: <%= stat[:value] %>  
    });
  <% end %>

  var width = $("#numDecksChart").width();
  var height = 500;
  var radius = Math.min(width, height) / 2;
  
  var color = d3.scale.ordinal()
      .range(["#D23F3F", "#354F8D", "#D2D23F", "#D28E3F", "#56358F", "#81BF3A", "#D2B23F", "#972D83", "#2A8B6E"]);  

  var arc = d3.svg.arc()
      .outerRadius(radius - 10)
      .innerRadius(0);

  var pie = d3.layout.pie()
      .sort(null)
      .value(function(d) { return d.value; });

  var svg = d3.select("#numDecksChart")
      .append("svg")
      .attr("width", width)
      .attr("height", height)
      .append("g");

  var g = svg.selectAll(".arc")
      .data(pie(data))
      .enter().append("g")
      .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")")
      .attr("class", "arc");

  g.append("path")
      .attr("d", arc)
      .style("fill", function(d) { return color(d.data.hero_name); });

  g.append("text")
      .attr("transform", function(d) { return "translate(" + arc.centroid(d) + ")"; })
      .attr("dy", ".35em")
      .style("text-anchor", "middle")
      .text(function(d) { return formatChartText(d.data); });

  var legend = svg.selectAll(".legend")
      .data(color.domain().slice().reverse())
      .enter().append("g")
      .attr("class", "legend")
      .attr("transform", function(d, i) { return "translate(0," + i * 20 + ")"; });

  var legendX = width / 2 + radius;
  var blockSize = 18;
  legend.append("rect")
      .attr("x", legendX)
      .attr("width", blockSize)
      .attr("height", blockSize)
      .style("fill", color);

  legend.append("text")
      .attr("x", legendX + blockSize + 2)
      .attr("y", 9)
      .attr("dy", ".35em")
      .style("text-anchor", "start")
      .text(formatLegendText);

  function formatLegendText(heroName) {
    var numRuns = data.filter(function(dataItem) { return dataItem.hero_name === heroName; })[0].value;
    return heroName + ': ' + numRuns;  
  }

  function formatChartText(data) {
    if(data.value > 0) {
      return data.hero_name;
    } else {
      return '';  
    }
  }
})();

</script>