config/routes.rb
Rails.application.routes.draw do
  resources :game_imports, :only => [:create, :destroy, :show, :index, :new]

  devise_for :users

  get 'arena_card_decks/stats' => 'arena_card_decks#stats'
  resources :arena_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  resources :regular_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  root :to => 'home#index'
end

app/models/game_import.rb
class GameImport < ActiveRecord::Base
  validates :user, :presence => true
  validates :file_name, :presence => true, :length => { :maximum => 64 }

  belongs_to :user
  has_many :games, :dependent => :destroy
  has_many :card_decks, :dependent => :destroy

  grant(:create, :find, :update, :destroy) { |user, model, action| !user.nil? && model.user_id == user.id }

  def num_games_imported
    self.games.count
  end
end

app/controllers/game_imports_controller.rb
require 'game_file_parser/csv'

class GameImportsController < ApplicationController

  before_action :set_active_tab
  before_action :set_game_import, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  FILE_PARSERS = [GameFileParser::Csv]

  # GET /game_imports
  # GET /game_imports.json
  def index
    @game_imports = current_user.game_imports.order(:created_at => :desc)
  end

  # GET /game_imports/1
  # GET /game_imports/1.json
  def show
    @heroes = Hero.all
  end

  # GET /game_imports/new
  def new
    @game_import = GameImport.new
    @import_errors = []
  end

  # GET /game_imports/1/edit
  def edit
  end

  # POST /game_imports
  # POST /game_imports.json
  def create
    @import_errors = []

    user_file = uploaded_file
    user_filename = user_file.nil? ? '' : user_file.original_filename
    if !user_file.nil?
      logger.info "User #{current_user.email} uploaded file #{user_file.class.name} with size #{user_file.size} bytes"

      parser = FILE_PARSERS.find do |parser|
        parser.can_parse?(user_file.content_type)
      end

      if parser.nil?
        @import_errors << 'Unable to parse file'
      else
        parser_instance = parser.new(user_file.tempfile, current_user)
        @game_import, @import_errors = parser_instance.process do |game_import|
          game_import.file_name = user_filename
        end
      end
    else
      @import_errors << 'No file given'
    end

    respond_to do |format|
      if !@game_import.nil?
        format.html { redirect_to @game_import, notice: 'Game import was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game_import }
      else
        @game_import = GameImport.new
        @game_import.file_name = user_filename
        format.html { render action: 'new' }
        format.json { render json: @game_import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_imports/1
  # DELETE /game_imports/1.json
  def destroy
    @game_import.destroy
    respond_to do |format|
      format.html { redirect_to game_imports_url }
      format.json { head :no_content }
    end
  end

  private

  def uploaded_file
    if params[:game_import] && params[:game_import][:file] && params[:game_import][:file].respond_to?(:original_filename)
      return params[:game_import][:file]
    else
      return nil
    end
  end

  def set_active_tab
    @active_tab = :game_imports
  end

  def set_game_import
    @game_import = GameImport.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_import_params
    #params.require(:game_import).permit()
    {}
  end
end

app/helpers/game_imports_helper.rb
module GameImportsHelper
end

app/views/game_imports/_form.html.erb
<%= form_for(@game_import) do |f| %>
  <% if @game_import.errors.any? || !@import_errors.empty? %>
    <div class="alert alert-danger">
      <ul>
      <% @game_import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

      <% @import_errors.each do |import_error| %>
        <li><%= import_error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="game_import_file">CSV File</label>
    <%= f.file_field :file %>
    <p class="help-block">File must be in comma seperated value (.csv) format.</p>
  </div>

  <div class="actions">
    <%= f.submit 'Import' %>
  </div>
<% end %>

app/views/game_imports/edit.html.erb
<h1>Editing game_import</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_import %> |
<%= link_to 'Back', game_imports_path %>

app/views/game_imports/index.html.erb
<h1>Game Imports</h1>

<table class="table">
  <thead>
    <tr>
      <th>File Name</th>
      <th># Games Imported</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_imports.each do |game_import| %>
      <tr class="link-row" data-href="<%= url_for game_import %>">
        <td><%= game_import.file_name %></td>
        <td><%= game_import.num_games_imported %></td>

        <td>
          <%= link_to(game_import, method: :delete, data: { confirm: 'Are you sure?' }) do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Import Games', new_game_import_path %>

app/views/game_imports/new.html.erb
<h1>Import Games</h1>

<%= render 'form' %>

<%= link_to 'Back', game_imports_path %>

app/views/game_imports/show.html.erb
<div class="row">
  <div class="info-panel">
    <table>
      <tr>
        <td class="right-align">File Name:</td><td class="left-padding"><%= @game_import.file_name %></td>
      </tr>
      <tr>
        <td class="right-align">Imported On:</td><td class="left-padding"><%= @game_import.created_at.to_formatted_s(:date) %></td>
      </tr>
    </table>
  </div>

  <h2>Imported</h2>
  <table class="table">
    <thead>
      <th>Deck Type</th>
      <th>Hero</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Start Date</th>
    </thead>

    <tbody>
      <% @game_import.card_decks.order(:created_at => :desc).each do |card_deck| %>
        <tr class="link-row" data-href="<%= url_for(card_deck)  -%>">
          <td><%= card_deck.class.name.underscore.humanize.split[0]  -%></td>
          <td><%= hero_name(card_deck) -%></td>
          <td><%= card_deck.num_games_won -%></td>
          <td><%= card_deck.num_games_lost -%></td>
          <td><%= card_deck.created_at.to_formatted_s(:date) -%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Back', game_imports_path %>
  </div>
<br/>