config/routes.rb
Rails.application.routes.draw do
  resources :game_imports, :only => [:create, :destroy, :show, :index, :new]

  devise_for :users

  get 'arena_card_decks/stats' => 'arena_card_decks#stats'
  resources :arena_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  resources :regular_card_decks do
    resources :games, :shallow => true, :only => [:create, :destroy]
  end

  root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeckFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Decker</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= @active_tab == :arena_card_deck ? 'active' : 'inactive'%>"><%= link_to 'Arena', arena_card_decks_path %></li>
        <li class="<%= @active_tab == :regular_card_deck ? 'active' : 'inactive'%>"><%= link_to 'Regular', regular_card_decks_path %></li>
        <li class="<%= @active_tab == :game_imports ? 'active' : 'inactive'%>"><%= link_to 'Import', game_imports_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="navbar-text">Signed in as <%= current_user.email %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :data => { :method => :delete } %></li>
        <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

    <div class="container">
      <div class="row">
        <% if (notice) %>
            <div class="alert alert-success notice"><%= notice %></div>
        <% end %>

        <% if (alert) %>
            <div class="alert alert-danger"><%= alert %></div>
        <% end %>

      </div>

      <%= yield %>
    </div>

</body>
</html>